# kube node to join master node

- name: Wait for master's port 6443
  wait_for: 
    host: "{{ hostvars['kubernetes']['ansible_default_ipv4']['address'] }}"
    port: 6443
    timeout: 1

- name: Join the cluster. Use log to prevent joining twice
  shell: "{{ hostvars['kubernetes'].join_command }} >> node_join.log"
  args:
    chdir: $HOME
    creates: node