# Initialize Cluster. The log is also used to prevent an second initialization
- name: Initialize Cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_init.log
  args:
    chdir: $HOME
    creates: cluster_init.log

# Create the configuration / configuration directory
- name: Create .kube directory
  become_user: vagrant
  become: yes
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to the user's kube directory
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes

- name: Setup Flannel. Use log to prevent second installation
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> flannel_setup.log
  args:
    chdir: $HOME
    creates: flannel_setup.log

- name: Create token to join cluster
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command as fact
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
