- name: Ensure 'man' directory exists.
  file:
    path: /usr/share/man/man1
    state: directory
    recurse: true

- name: Ensure Java is installed.
  apt:
    name: "{{ java_packages }}"
    state: present